---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configurations
spec:
  # selector:
  #   matchLabels:
  #     app: sb-11
  storageClassName: node0-local-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi

...
