---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
spec:
  # selector:
  #   matchLabels:
  #     app: sb-11
  storageClassName: node0-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

...
