---
apiVersion: v1
kind: Pod
metadata:
  name: downwardapiev
  labels:
    app: downwardapiapp
    color: red 

spec:
  containers:
    # ---------------------------
    - name: downwardapiev-01
      image: busybox:1.36
      command: ["sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          if [[ -e /etc/containerinfo/cpu_limit ]]; then
            echo -en '\n'; cat /etc/containerinfo/cpu_limit; fi;
          if [[ -e /etc/containerinfo/cpu_request ]]; then
            echo -en '\n'; cat /etc/containerinfo/cpu_request; fi;
          if [[ -e /etc/containerinfo/mem_limit ]]; then
            echo -en '\n'; cat /etc/containerinfo/mem_limit; fi;
          if [[ -e /etc/containerinfo/mem_request ]]; then
            echo -en '\n'; cat /etc/containerinfo/mem_request; fi;
          sleep 5;
        done;
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: containerinfo
          mountPath: /etc/containerinfo

    # ---------------------------
    - name: downwardapiev-02
      image: busybox:1.36
      command: ["sh", "-c"]
      args:
      - while true; do
          if [[ -e /etc/podinfo/labels ]]; then
            echo -en '\n\n'; cat /etc/podinfo/labels; fi;
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\n'; cat /etc/podinfo/annotations; fi;
          sleep 5;
        done;
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo

  volumes:
    # ---------------------------
    - name: containerinfo
      downwardAPI:
        items:
          - path: "cpu_limit"
            resourceFieldRef:
              containerName: downwardapiev-01
              resource: limits.cpu
              divisor: 1m
          - path: "cpu_request"
            resourceFieldRef:
              containerName: downwardapiev-01
              resource: requests.cpu
              divisor: 1m
          - path: "mem_limit"
            resourceFieldRef:
              containerName: downwardapiev-01
              resource: limits.memory
              divisor: 1Mi
          - path: "mem_request"
            resourceFieldRef:
              containerName: downwardapiev-01
              resource: requests.memory
              divisor: 1Mi

    # ---------------------------
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations

...

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: eev
# spec:
#   containers:
#   - image: busybox:1.36
#     name: eev-01
#     volumeMounts:
#     - mountPath: "/scratch"
#       name: scratch-volume
#     command: [ "tail", "-f", "/dev/null" ]
#     resources:
#       limits:
#         memory: 32Mi
#         cpu: 100m
#   volumes:
#   - name: scratch-volume
#     emptyDir:
#       sizeLimit: 500Mi

# ...

