---
apiVersion: v1
kind: Pod
metadata:
  name: eev
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: eev-01
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    resources:
      limits:
        memory: 32Mi
        cpu: 100m
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi

...

