# Generic Ephemeral Volume
---
kind: Pod
apiVersion: v1
metadata:
  name: evap
spec:
  containers:
    - name: evap-01
      image: busybox:1.36
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command: [ "tail", "-f", "/dev/null" ]
      resources:
        limits:
          memory: 32Mi
          cpu: 100m
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: evap-01-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "scratch-storage-class"
            resources:
              requests:
                storage: 2Gi

...


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: m8-local-storage-ephemeral
  labels:
    file-system: ext4
    physical-volume: lvm-partition
    max-size: 1Gi
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: scratch-storage-class
  local:
    path: /home/zoosman/dev/k0s/volumes/mnt/ephemerals/1G
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp8

...


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: m8-local-storage-ephemeral2
  labels:
    file-system: ext4
    physical-volume: lvm-partition
    max-size: 4Gi
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: scratch-storage-class
  local:
    path: /home/zoosman/dev/k0s/volumes/mnt/ephemerals/4G
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp8

...