---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: m8-local-storage-monitoring
  labels:
    file-system: ext4
    physical-volume: lvm-partition
    max-size: 20Gi
    app: sb-11
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: node0-local-storage-monitoring
  local:
    path: /home/zoosman/dev/k0s/volumes/mnt/monitoring
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp8

...
