---
apiVersion: batch/v1
kind: Job
metadata:
  name: jtest
spec:
  parallelism: 3
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: jtest-01
        image: busybox:1.37
        command: ["sh", "-c", "sleep 10; echo \"Hello World!\""]
      restartPolicy: Never

...
