---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sb-11-monitoring-data
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: sb-11
  storageClassName: node0-local-storage-monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

...

